spring:
  cloud:
    function:
      configuration:
        # Demonstrating that the wonted behavior simply do nothing.
        demoBinding:
          output-header-mapping-expression:
            timeToLive: 23000L
            senderId: myApplicationName
    stream:
      bindings:
        demoBinding-out-0:
          destination: target-topic
          binder: test
